### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by adebsa2401** [adebsa2401/SpaceX-Hub#25]
Link: [https://github.com/adebsa2401/SpaceX-Hub/projects/1](https://github.com/adebsa2401/SpaceX-Hub/projects/1)
Team size: 2

**Comment by mckent05** [comment]
Hi @adebsa2401, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- Good job setting up your Kanban board 👏 👏 


## Required Changes ♻️
- According to the project requirements, students should have cards with all required categories in their titles:
  --Required categories:`Setup`, `Fetch data`, `Lists render`, `Actions`, `Conditional components`, `Filters` i.e Each student should have cards with each of the above-listed categories assigned to them. Please fix this 🙏 🙏 
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mckent05** [comment]
Hi team, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All tasks have been assigned fairly 👍 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
